
.ifndef	__PPUDRV_INC__

.define	__PPUDRV_INC__

	.importzp	__PPUDRV_S0_Pt
	.importzp	__PPUDRV_D0_Pt
	.importzp	__PPUDRV_S1_Pt
	.importzp	__PPUDRV_D1_Pt
	.importzp	__PPUDRV_S2_Pt
	.importzp	__PPUDRV_D2_Pt
	.importzp	__PPUDRV_S3_Pt
	.importzp	__PPUDRV_D3_Pt
	
	.importzp	__PPUDRV_T0_Cnt
	.importzp	__PPUDRV_T1_Cnt
	.importzp	__PPUDRV_T2_Cnt
	.importzp	__PPUDRV_T3_Cnt
	
	.importzp	__PPUDRV_Sprite_Flag
	.importzp	__PPUDRV_IRQ_Line
	.importzp	__PPUDRV_Scroll_x
	.importzp	__PPUDRV_Scroll_y

	.importzp	__PPUDRV_Cbank0
	.importzp	__PPUDRV_Cbank1
	.importzp	__PPUDRV_Cbank2
	.importzp	__PPUDRV_Cbank3
	.importzp	__PPUDRV_Cbank4
	.importzp	__PPUDRV_Cbank5

.endif
